### ISSUE TITLE
Creating a legend in Geoserver?

### ISSUE THREAD

**Issue by epyks23** [geoserver/geoserver.github.io#30]
(Please let me know if this post is in the wrong place).

I created a map in Geoserver and I have a lot of layeres.

How can I add a legend to it (hopefully without using code)? I want the user to be able to switch layers on and off.

**Comment by bencaradocdavies** [comment]
@epyks23 please send your question to the geoserver-users mailing list. This issue tracker is used for problems with the geoserver web site. This question is on-topic for the geoserver-users mailing list.
