### ISSUE TITLE
update FOSS4G logo

### ISSUE THREAD

**Issue by jmckenna** [geoserver/geoserver.github.io#39]
Please change the FOSS4G logo displayed on the main page to point to the 2017 logo.  For the logo you can grab it from http://foss4g.org or http://mapserver.org (left panel).  Point to http://2017.foss4g.org/ 

Thanks.

**Comment by tbarsballe** [comment]
Resolved with https://github.com/geoserver/geoserver.github.io/commit/b38fe0c8dc8052b9c1982814babd7a879244c9ae and https://github.com/geoserver/geoserver.github.io/commit/6fd9f0fbec0262b51ba884e1d4fdf5999a44549a.

**Comment by jmckenna** [comment]
thanks @tbarsballe !
