### ISSUE TITLE
 Geoserver doesn't render all features in some zooms 

### ISSUE THREAD

**Issue by yedagi** [geoserver/geoserver.github.io#53]
hi,
im using geoserver 2.11.0, with elasticsearch as datasource.
i also use leaflet vector tiles plugin to request the tiles.

i have noticed that when use leaflet map controller, in certain zooms the geoserver doesn't return all geometries (in deeper zoom it shows more geometries).
i checked with wireshark the result the geoserver recieves from elasticsearch, and it recieves the same geometries in both zoom levels.
i wondered if there is some configuration that determine whether the geoserver "ignore" geometries in low zoom to simplify the response ?

any ideas how to solve my problem ?

**Comment by aaime** [comment]
This project hosts the GeoServer web site (geoserver.org), so the ticket will be ignored.
GeoServer does not have an official elasticsearch data source, I believe NGA is providing one. I'd suggest to ask there.

**Comment by bencaradocdavies** [comment]
@yedagi you could also ask on the geoserver-users mailing list.
