### ISSUE TITLE
Rest docs are 404

### ISSUE THREAD

**Issue by robmarkcole** [geoserver/geoserver.github.io#68]
Nearly all links on https://docs.geoserver.org/latest/en/user/rest/index.html#rest are 404

**Comment by chrismayer** [comment]
Seems to be OK on https://docs.geoserver.org/latest/en/user/rest/index.html#rest but I can reproduce the broken links on

https://docs.geoserver.org/stable/en/user/rest/index.html 
and
https://docs.geoserver.org/maintain/en/user/rest/index.html

**Comment by aaime** [comment]
Duplicates https://osgeo-org.atlassian.net/browse/GEOS-9002
