### ISSUE TITLE
Geoserver plugin error when creating new geowave data store

### ISSUE THREAD

**Issue by byungwok** [geoserver/geoserver.github.io#69]
Hi thank you for your last answer. i did set it up clearly with cdh5.

Now i'm asking and also reporting about a strange phenomenon at geowave-geoserver plugin.
Geosever does not make a new Geowave Datastore -ACCUMULO through geoserver web. but in the opposite case, in other words, that it's ok to type in geowave CLI 'geowave gs addlayer [storename] [opsition]' on the geowave site. Even if i fill in the same connection info already created by geowave CLI, it'd say same error that 'Error obtaining new data store' or sometimes check the jar fill in /lib dir.
I tried to fix the geowave-geoserver jar file, tools jar or geoserver, but it's in vain.
I have no idea what other people also do. so i have a question about it 'have u seen this error before?' and 'how to fix it?'

version info;
geoserver : 2.13.2
geowave tools jar: 1.0.0-cdh5-tools
geowave accumulo jar : 1.0.0-cdh5-accumulo
geowave geoserver jar : deploy-1.0.0-geoserver ('1.0.0-cdh5-geoserver' is not work at geoserver. The 'gs addlayer' command is not accepted with 404 or 500 error.)
cdh5 name node with accumulo and geoserver is different device. but no matter to ping-pong with cdh5 zookeeper like 'ingest' on cli

it's the logs on geoserver create geowave data store;
default
![47264120-eae56b00-d54a-11e8-90b9-4537b4815d35](https://user-images.githubusercontent.com/39606428/48055706-905b3880-e1f3-11e8-87fd-0ed8834692e8.PNG)

Please let me know about it what happen at geoserver and geowave

**Comment by aaime** [comment]
This ticket tracker is for the geoserver web site itself (the pages making up the contents of geoserver.org).
For a bug report about geowave please go on the geowave web site, the GeoServer community is not involved at all with that plugin
